/*
 * Edge AI–Based Anomaly Detection System
 * Hardware: ESP32
 * Framework: ESP-IDF + FreeRTOS + TensorFlow Lite for Microcontrollers
 *
 * A Python-trained anomaly detection model (autoencoder) is converted to
 * TensorFlow Lite and runs entirely on-device. No cloud round-trip needed
 * for inference — only anomaly alerts are transmitted.
 *
 * Pipeline:
 *   Sensor read → Preprocess → TFLite inference → Anomaly check → Alert
 */

#include <stdio.h>
#include <string.h>
#include <math.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "driver/adc.h"
#include "driver/gpio.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "mqtt_client.h"

/* TensorFlow Lite for Microcontrollers C API */
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

/* Quantised TFLite model — generated by convert_model.py */
#include "model_data.h"
#include "config.h"

static const char *TAG = "EDGE_AI";

/* TFLite globals */
static const tflite::Model* tflite_model;
static tflite::MicroInterpreter* interpreter;
static TfLiteTensor* input_tensor;
static TfLiteTensor* output_tensor;

/* Tensor arena — statically allocated on-device (no heap) */
static uint8_t tensor_arena[TENSOR_ARENA_SIZE];

/* Queue for raw sensor readings */
static QueueHandle_t raw_data_queue;

/* MQTT */
static esp_mqtt_client_handle_t mqtt_client;
static bool mqtt_connected = false;

/* ─────────────────────────────────────────────
 *  TensorFlow Lite Initialisation
 * ───────────────────────────────────────────── */
static esp_err_t tflite_init(void)
{
    tflite_model = tflite::GetModel(g_model_data);
    if (tflite_model->version() != TFLITE_SCHEMA_VERSION) {
        ESP_LOGE(TAG, "Model schema version mismatch: %d vs %d",
                 tflite_model->version(), TFLITE_SCHEMA_VERSION);
        return ESP_FAIL;
    }

    /* Register only the ops used by this model to save flash */
    static tflite::MicroMutableOpResolver<4> resolver;
    resolver.AddFullyConnected();
    resolver.AddRelu();
    resolver.AddQuantize();
    resolver.AddDequantize();

    static tflite::MicroInterpreter static_interpreter(
        tflite_model, resolver, tensor_arena, TENSOR_ARENA_SIZE);
    interpreter = &static_interpreter;

    if (interpreter->AllocateTensors() != kTfLiteOk) {
        ESP_LOGE(TAG, "AllocateTensors() failed — increase TENSOR_ARENA_SIZE");
        return ESP_FAIL;
    }

    input_tensor  = interpreter->input(0);
    output_tensor = interpreter->output(0);

    ESP_LOGI(TAG, "TFLite model loaded. Input shape: [1 x %d]", input_tensor->dims->data[1]);
    return ESP_OK;
}

/* ─────────────────────────────────────────────
 *  Preprocessing: normalise raw ADC values to [-1, 1]
 *  Model was trained on data in this range.
 * ───────────────────────────────────────────── */
static void preprocess(const float *raw, float *normalised, int len)
{
    for (int i = 0; i < len; i++) {
        normalised[i] = (raw[i] - ADC_MEAN) / ADC_STD;
    }
}

/* ─────────────────────────────────────────────
 *  Run TFLite Inference
 *  Autoencoder: input == output when normal
 *  Reconstruction error > threshold → anomaly
 * ───────────────────────────────────────────── */
static float run_inference(const float *features, int feature_len)
{
    /* Copy normalised features into input tensor */
    for (int i = 0; i < feature_len; i++) {
        input_tensor->data.f[i] = features[i];
    }

    if (interpreter->Invoke() != kTfLiteOk) {
        ESP_LOGE(TAG, "TFLite inference failed");
        return -1.0f;
    }

    /* Compute mean squared reconstruction error */
    float mse = 0.0f;
    for (int i = 0; i < feature_len; i++) {
        float diff = input_tensor->data.f[i] - output_tensor->data.f[i];
        mse += diff * diff;
    }
    return mse / feature_len;
}

/* ─────────────────────────────────────────────
 *  MQTT Helpers
 * ───────────────────────────────────────────── */
static void mqtt_event_handler(void *arg, esp_event_base_t base,
                               int32_t event_id, void *event_data)
{
    esp_mqtt_event_handle_t event = event_data;
    if (event->event_id == MQTT_EVENT_CONNECTED) {
        mqtt_connected = true;
        ESP_LOGI(TAG, "MQTT connected");
    }
}

static void mqtt_init(void)
{
    esp_mqtt_client_config_t cfg = { .broker.address.uri = MQTT_BROKER_URI };
    mqtt_client = esp_mqtt_client_init(&cfg);
    esp_mqtt_client_register_event(mqtt_client, ESP_EVENT_ANY_ID, mqtt_event_handler, NULL);
    esp_mqtt_client_start(mqtt_client);
}

static void publish_anomaly_alert(float recon_error, const float *features)
{
    if (!mqtt_connected) return;
    char payload[256];
    snprintf(payload, sizeof(payload),
             "{\"anomaly\":true,\"recon_error\":%.4f,\"f0\":%.3f,\"f1\":%.3f,\"f2\":%.3f}",
             recon_error, features[0], features[1], features[2]);
    esp_mqtt_client_publish(mqtt_client, MQTT_ALERT_TOPIC, payload, 0, 1, 0);
    ESP_LOGW(TAG, "ANOMALY ALERT published: error=%.4f", recon_error);
}

/* ─────────────────────────────────────────────
 *  WiFi (minimal, same pattern as other projects)
 * ───────────────────────────────────────────── */
static SemaphoreHandle_t wifi_sem;
static void wifi_handler(void *a, esp_event_base_t b, int32_t id, void *d)
{
    if (b == WIFI_EVENT && id == WIFI_EVENT_STA_START) esp_wifi_connect();
    else if (b == IP_EVENT && id == IP_EVENT_STA_GOT_IP) xSemaphoreGive(wifi_sem);
    else if (b == WIFI_EVENT && id == WIFI_EVENT_STA_DISCONNECTED) esp_wifi_connect();
}

static void wifi_init(void)
{
    wifi_sem = xSemaphoreCreateBinary();
    esp_netif_init();
    esp_event_loop_create_default();
    esp_netif_create_default_wifi_sta();
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    esp_wifi_init(&cfg);
    esp_event_handler_register(WIFI_EVENT, ESP_EVENT_ANY_ID, wifi_handler, NULL);
    esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, wifi_handler, NULL);
    wifi_config_t wc = { .sta = { .ssid = WIFI_SSID, .password = WIFI_PASSWORD } };
    esp_wifi_set_mode(WIFI_MODE_STA);
    esp_wifi_set_config(WIFI_IF_STA, &wc);
    esp_wifi_start();
    xSemaphoreTake(wifi_sem, portMAX_DELAY);
}

/* ─────────────────────────────────────────────
 *  Task 1: Sensor Acquisition Task
 *  Collects N ADC samples → sends window to inference task
 * ───────────────────────────────────────────── */
typedef struct {
    float samples[FEATURE_LENGTH];
} sensor_window_t;

static void sensor_task(void *pvParameters)
{
    adc1_config_width(ADC_WIDTH_BIT_12);
    adc1_config_channel_atten(SENSOR_ADC_CHANNEL, ADC_ATTEN_DB_11);

    sensor_window_t window;
    int idx = 0;

    ESP_LOGI(TAG, "Sensor task started, collecting windows of %d samples", FEATURE_LENGTH);

    while (1) {
        int raw = adc1_get_raw(SENSOR_ADC_CHANNEL);
        window.samples[idx++] = (float)raw;

        if (idx >= FEATURE_LENGTH) {
            idx = 0;
            /* Send full window to inference task (overwrite old if queue full) */
            xQueueOverwrite(raw_data_queue, &window);
        }

        vTaskDelay(pdMS_TO_TICKS(SAMPLE_INTERVAL_MS));
    }
}

/* ─────────────────────────────────────────────
 *  Task 2: Inference Task
 *  Preprocesses window → runs TFLite → checks threshold
 * ───────────────────────────────────────────── */
static void inference_task(void *pvParameters)
{
    sensor_window_t window;
    float normalised[FEATURE_LENGTH];

    ESP_LOGI(TAG, "Inference task started");

    while (1) {
        if (xQueueReceive(raw_data_queue, &window, portMAX_DELAY) == pdTRUE) {
            preprocess(window.samples, normalised, FEATURE_LENGTH);

            float recon_error = run_inference(normalised, FEATURE_LENGTH);

            ESP_LOGI(TAG, "Reconstruction error: %.4f (threshold: %.4f)",
                     recon_error, ANOMALY_THRESHOLD);

            if (recon_error > ANOMALY_THRESHOLD) {
                publish_anomaly_alert(recon_error, normalised);
                gpio_set_level(ALERT_LED_GPIO, 1);
                vTaskDelay(pdMS_TO_TICKS(500));
                gpio_set_level(ALERT_LED_GPIO, 0);
            }
        }
    }
}

/* ─────────────────────────────────────────────
 *  app_main
 * ───────────────────────────────────────────── */
void app_main(void)
{
    ESP_LOGI(TAG, "=== Edge AI Anomaly Detection System ===");

    ESP_ERROR_CHECK(nvs_flash_init());

    /* Initialise TFLite before starting tasks */
    ESP_ERROR_CHECK(tflite_init());

    gpio_set_direction(ALERT_LED_GPIO, GPIO_MODE_OUTPUT);

    /* Queue holds 1 window (overwrite pattern — always latest data) */
    raw_data_queue = xQueueCreate(1, sizeof(sensor_window_t));

    wifi_init();
    mqtt_init();

    xTaskCreate(sensor_task,    "sensor_task",    4096, NULL, 5, NULL);
    xTaskCreate(inference_task, "inference_task", 8192, NULL, 4, NULL);

    ESP_LOGI(TAG, "System running. Monitoring for anomalies...");
}
