"""
train_and_convert.py
====================
Trains a simple autoencoder for anomaly detection on sensor data,
then converts it to TensorFlow Lite (int8 quantised) for ESP32 deployment.

Usage:
    python train_and_convert.py --data sensor_data.csv --output model_data.h
"""

import argparse
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import os

# ─────────────────────────────────────────────────────────────────────────────
# 1. Load and Preprocess Data
# ─────────────────────────────────────────────────────────────────────────────

def load_data(csv_path, feature_length=16, train_ratio=0.8):
    """
    Load sensor CSV and create sliding windows.
    CSV should have a single column 'sensor_value'.
    """
    df = pd.read_csv(csv_path)
    values = df['sensor_value'].values.astype(np.float32)

    # Normalise to [-1, 1]
    mean = values.mean()
    std  = values.std()
    values_norm = (values - mean) / std

    print(f"Data stats — mean: {mean:.2f}, std: {std:.2f}")
    print(f"Write these to config.h: ADC_MEAN={mean:.4f}, ADC_STD={std:.4f}")

    # Create sliding windows
    windows = []
    for i in range(len(values_norm) - feature_length):
        windows.append(values_norm[i : i + feature_length])
    windows = np.array(windows)

    # Train only on NORMAL data (autoencoder learns normal distribution)
    split = int(len(windows) * train_ratio)
    return windows[:split], windows[split:], mean, std


# ─────────────────────────────────────────────────────────────────────────────
# 2. Build Autoencoder
# ─────────────────────────────────────────────────────────────────────────────

def build_autoencoder(feature_length):
    """
    Symmetric autoencoder.
    Encoder compresses to a bottleneck — decoder reconstructs.
    High reconstruction error = anomaly.
    """
    inputs  = keras.Input(shape=(feature_length,))
    # Encoder
    x = keras.layers.Dense(8, activation='relu')(inputs)
    x = keras.layers.Dense(4, activation='relu')(x)
    # Decoder
    x = keras.layers.Dense(8, activation='relu')(x)
    outputs = keras.layers.Dense(feature_length, activation='linear')(x)

    model = keras.Model(inputs, outputs, name='autoencoder')
    model.compile(optimizer='adam', loss='mse')
    return model


# ─────────────────────────────────────────────────────────────────────────────
# 3. Train
# ─────────────────────────────────────────────────────────────────────────────

def train(model, X_train, X_val, epochs=50, batch_size=32):
    callbacks = [
        keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True),
        keras.callbacks.ReduceLROnPlateau(factor=0.5, patience=3)
    ]
    history = model.fit(
        X_train, X_train,           # Target = input (reconstruction)
        validation_data=(X_val, X_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=callbacks,
        verbose=1
    )
    return history


# ─────────────────────────────────────────────────────────────────────────────
# 4. Determine Anomaly Threshold
#    Use 95th percentile of reconstruction errors on normal validation data
# ─────────────────────────────────────────────────────────────────────────────

def compute_threshold(model, X_val):
    preds = model.predict(X_val)
    errors = np.mean((X_val - preds) ** 2, axis=1)
    threshold = np.percentile(errors, 95)
    print(f"\nAnomaly threshold (95th percentile): {threshold:.6f}")
    print(f"Write this to config.h: ANOMALY_THRESHOLD={threshold:.6f}f")
    return threshold


# ─────────────────────────────────────────────────────────────────────────────
# 5. Convert to TFLite (int8 quantised)
# ─────────────────────────────────────────────────────────────────────────────

def convert_to_tflite(model, X_train, output_h_path):
    def representative_dataset():
        for sample in X_train[:200]:
            yield [sample.reshape(1, -1).astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.float32
    converter.inference_output_type = tf.float32

    tflite_model = converter.convert()

    # Save .tflite binary
    tflite_path = output_h_path.replace('.h', '.tflite')
    with open(tflite_path, 'wb') as f:
        f.write(tflite_model)
    print(f"\nTFLite model saved: {tflite_path} ({len(tflite_model)} bytes)")

    # Convert binary to C header array for embedding in firmware
    hex_array = ', '.join(f'0x{b:02x}' for b in tflite_model)
    c_header = f"""// Auto-generated by convert_model.py — do not edit manually
// Model size: {len(tflite_model)} bytes

#pragma once
#include <stdint.h>

const uint8_t g_model_data[] = {{
  {hex_array}
}};
const uint32_t g_model_data_len = {len(tflite_model)};
"""
    with open(output_h_path, 'w') as f:
        f.write(c_header)
    print(f"C header written: {output_h_path}")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data',    default='sensor_data.csv')
    parser.add_argument('--output',  default='model_data.h')
    parser.add_argument('--epochs',  type=int, default=50)
    parser.add_argument('--feature_length', type=int, default=16)
    args = parser.parse_args()

    print("=== Edge AI Anomaly Detection — Model Training ===\n")

    X_train, X_val, mean, std = load_data(args.data, args.feature_length)
    print(f"Training samples: {len(X_train)}, Validation samples: {len(X_val)}\n")

    model = build_autoencoder(args.feature_length)
    model.summary()

    train(model, X_train, X_val, epochs=args.epochs)

    threshold = compute_threshold(model, X_val)

    convert_to_tflite(model, X_train, args.output)

    print("\n=== Done ===")
    print(f"1. Copy {args.output} to your ESP-IDF project main/ folder")
    print(f"2. Set ANOMALY_THRESHOLD {threshold:.6f}f in config.h")
    print(f"3. Set ADC_MEAN {mean:.4f}f and ADC_STD {std:.4f}f in config.h")
